version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - erum

networks:
  erum:
    driver: bridge
